export type TcgCsvProduct = {
  productId: number;
  name: string;
  cleanName: string;
  imageUrl: string;
  categoryId: number;
  groupId: number;
  url: string;
  modifiedOn: string;
  marketPrice: number | null | string;
  directLowPrice: number | null;
  avgPrice: number | null;
  foilPrice: number | null;
  normalPrice: number | null;
  etchedPrice: number | null;
  tcgplayerProductId?: string;
  tcgplayerEtchedProductId?: string;
  cardKingdomId?: string;
  cardKingdomFoilId?: string;
  cardKingdomEtchedId?: string;
  cardsphereId?: string;
  cardsphereFoilId?: string;
  cardtraderId?: string;
  csiId?: string;
  mcmId?: string;
  mcmMetaId?: string;
  miniaturemarketId?: string;
  mtgArenaId?: string;
  mtgjsonFoilVersionId?: string;
  mtgjsonNonFoilVersionId?: string;
  mtgjsonV4Id?: string;
  mtgoFoilId?: string;
  mtgoId?: string;
  multiverseId?: string;
  scgId?: string;
  scryfallId?: string;
  scryfallCardBackId?: string;
  scryfallOracleId?: string;
  scryfallIllustrationId?: string;
  tntId?: string;
};
